# https://taskfile.dev

version: "3"

tasks:
  update-flake-inputs:
    desc: "Updates all flake inputs."
    cmds:
      - nix flake update
  push-to-burger-builder:
    desc: >-
      Force push any changes on monorepo-playground/main to
      monorepo-burger-playground/main.
    cmds:
      - copybara --github-api-bearer-auth=true --nogit-prompt copy.bara.sky push
  pr-from-burger-builder:
    desc: >-
      Make a pull request from any changes in monorepo-burger-playground/main
      to monorepo-playground/main.
    cmds:
      - copybara --github-api-bearer-auth=true --nogit-prompt copy.bara.sky pr
  validate-copybara:
    desc: "Ensures the copy.bara.sky file is valid."
    cmds:
      - copybara validate copy.bara.sky
  super-lint:
    desc: Run GitHub super linter.
    cmds:
      - >-
        sudo docker run
        -e LOG_LEVEL=INFO
        -e RUN_LOCAL=true
        -e DEFAULT_BRANCH=main
        -v $(pwd):/tmp/lint
        --rm
        ghcr.io/super-linter/super-linter:latest
  super-format:
    desc: Run GitHub super linter with all fix enabled.
    cmds:
      - >-
        sudo docker run
        -e LOG_LEVEL=INFO
        -e RUN_LOCAL=true
        -e DEFAULT_BRANCH=main
        -e FIX_YAML_PRETTIER=true
        -e FIX_MARKDOWN=true
        -e FIX_MARKDOWN_PRETTIER=true
        -e FIX_BIOME_FORMAT=true
        -e FIX_CLANG_FORMAT=true
        -v $(pwd):/tmp/lint
        --rm
        ghcr.io/super-linter/super-linter:latest
